swagger: '2.0'
info:
  title: Argent Bank Transactions API
  description: API model proposal for user transactions
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'

host: localhost:3001
basePath: /api/v2
schemes:
  - http

paths:
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: List of user accounts
      description: Get an array with one object per account with general info.
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        type: string
      produces:
        - application/json
      responses:
        '200':
          description: All the accounts retrieved successfully
          schema:
              $ref: '#/definitions/AccountsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /accounts/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: List of one account transactions
      description: Retrieves an account identification checking in parameters to returns an array with all the associated transactions.
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        type: string
      - in: path
        name: accountId
        description: An account identification checking id
        required: true
        type: string
      produces:
        - application/json
      responses:
        '200':
          description: All the transactions retrieved successfully
          schema:
              $ref: '#/definitions/AccountResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{accountId}/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction info
      description: Allows user to modify the editable info of a transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in : path
          name : accountId
          description: An account identification checking id
          required: true
          type: string
        - in : path
          name : transactionId
          description: A transaction id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction editable info
      description: Allows user to complete, modify or delete the editable info of a transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in : path
          name : accountId
          description: An account identification checking id
          required: true
          type: string
        - in : path
          name : transactionId
          description: A transaction id
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction info
          required: true
          schema:
            $ref: '#/definitions/TransactionDetails'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:

  Accounts:
    properties:
      accountId:
        type: string
        description: account bank checking
      balance:
        type: number
        description: account balance

  AccountsResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          account1:
            type: object
            properties:
              checking:
                type: string
                description: account bank checking
              balance:
                type: number
                description: account balance
          account2:
            type: object
            properties:
              checking:
                type: string
                description: account bank checking
              balance:
                type: number
                description: account balance
  
  Account:
    properties:
      year:
        type: object
        properties:
          mounth:
            type: object
            properties:
             day:
              type: object
              properties:
                transaction:
                  type: object
                  properties:
                    id:
                      type: string
                      description: transaction id
                    date:
                      type: string
                      description: transaction date
                    description:
                      type: string
                      description: transaction description
                    amount:
                      type: string
                      description: transaction amount
                    balance:
                      type: string
                      description: transaction balance
                    category:
                      type: string
                      description: editable transaction category
                    notes:
                      type: string
                      description: editable transaction notes

  Transaction:
    properties:
      id:
        type: string
        description: transaction id
      date:
        type: string
        description: transaction date
      description:
        type: string
        description: transaction description
      amount:
        type: string
        description: transaction amount
      balance:
        type: string
        description: transaction balance
      category:
        type: string
        description: editable transaction category
      notes:
        type: string
        description: editable transaction notes
        
  AccountResponse:
    properties:
      year:
        type: object
        properties:
          mounth:
            type: object
            properties:
             day:
              type: object
              properties:
                transaction1:
                  type: object
                  properties:
                    id:
                      type: string
                      description: transaction id
                    date:
                      type: string
                      description: transaction date
                    description:
                      type: string
                      description: transaction description
                    amount:
                      type: string
                      description: transaction amount
                    balance:
                      type: string
                      description: transaction balance
                    category:
                      type: string
                      description: editable transaction category
                    notes:
                      type: string
                      description: editable transaction notes
                transaction2:
                  type: object
                  properties:
                    id:
                      type: string
                      description: transaction id
                    date:
                      type: string
                      description: transaction date
                    description:
                      type: string
                      description: transaction description
                    amount:
                      type: string
                      description: transaction amount
                    balance:
                      type: string
                      description: transaction balance
                    category:
                      type: string
                      description: editable transaction category
                    notes:
                      type: string
                      description: editable transaction notes
  
  TransactionDetails:
    properties:
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: transaction notes

  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: transaction id
          date:
            type: string
            description: transaction date
          description:
            type: string
            description: transaction description
          amount:
            type: string
            description: transaction amount
          balance:
            type: string
            description: transaction balance
          category:
            type: string
            description: editable transaction category
          notes:
            type: string
            description: editable transaction notes
